## 3주차 미션 - Numpy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Q1. 본격적으로 Numpy와 친해지기 위해서 다양한 연산을 연습해볼 예정입니다. **무작위의 데이터를 가진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행렬곱 연산**을 진행해보세요.

```python
import numpy as np

arr1 = #TODO
arr2 = #TODO

dot = # TODO
```
```bash
# 출력 예시
>>> print(dot, dot.shape) # 결과 값은 달라질 수 있으나, 연산 후 shape는 일정해야 한다.
[[0.25 1.97]
 [0.11 0.96]
 [0.50 0.37]
 [0.28 0.23]
 [0.39 0.83]] (5, 2)
```

### A1.

In [ ]:
import numpy as np

# 5x3 크기의 난수 어레이 생성
arr1 = np.random.rand(5,3)
# 3x2 크기의 난수 어레이 생성
arr2 = np.random.rand(3,2)

# Answer1
# np.dot 함수를 사용하여 행렬곱 연산
# 5x3 * 3x2 -> 5x2 크기의 행렬 생성
dot = np.dot(arr1, arr2)

# Answer2
# np.matmul 함수를 사용하여 행렬곱 연산
matmul = np.matmul(arr1, arr2)

# Answer3
# @ 연산자를 사용하여 행렬곱 연산
mul_operator = arr1@arr2

# 결과 출력
print('[Answer 1] np.dot 연산 결과\n', dot, dot.shape, '\n')
print('[Answer 2] np.matmul 연산 결과\n', matmul, matmul.shape, '\n')
print('[Answer 3] @ 연산 결과\n', mul_operator, mul_operator.shape)

[Answer 1] np.dot 연산 결과
 [[0.67918064 0.8289918 ]
 [0.76524298 0.57636109]
 [0.83350684 0.93614632]
 [0.79505904 0.7607289 ]
 [0.95061547 1.22979121]] (5, 2) 

[Answer 2] np.matmul 연산 결과
 [[0.67918064 0.8289918 ]
 [0.76524298 0.57636109]
 [0.83350684 0.93614632]
 [0.79505904 0.7607289 ]
 [0.95061547 1.22979121]] (5, 2) 

[Answer 3] @ 연산 결과
 [[0.67918064 0.8289918 ]
 [0.76524298 0.57636109]
 [0.83350684 0.93614632]
 [0.79505904 0.7607289 ]
 [0.95061547 1.22979121]] (5, 2)


❗ 2차원 공간까지는 dot (내적) 연산과 행렬곱 연산(matmul, @)이 동일하나,   
3차원 공간부터는 달라지니 주의할 것!

### Q2. 두번째로는 numpy에서 자주 사용하는 concatenate 연산에 대한 미션을 수행해보겠습니다. 이제 Numpy에서 사용하는 2개의 numpy array가 있을 때, **두 numpy array의 concatenate 연산**을 구해보세요. 
- axis는 0, 1 두개로 연산한 결과를 출력해보세요.
- 각 데이터가 어떤 형태로 더해지는지 확인해보세요.

```python
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = # TODO axis 0
concat_2 = # TODO axis 1
```

```bash
# 출력 예시
>>>
[[5. 7.]
 [9. 11.]
 [2. 4.]
 [6. 8.]]
[[5. 7. 2. 4.]
 [9. 11. 6. 8.]]
```


### A2.

In [ ]:
# 2x2 크기의 실수 타입 numpy array 선언
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

# 각각 axis 0, axis 1 방향으로 concatenation 진행
concat_1 = np.concatenate((arr1, arr2), axis=0) # axis 0
concat_2 = np.concatenate((arr1, arr2), axis=1) # axis 1

# 결과 값 출력
print(f'concat_1 (axis=0):\n {concat_1}\n')
print(f'concat_2 (axis=1):\n {concat_2}')

concat_1 (axis=0):
 [[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]

concat_2 (axis=1):
 [[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


### Q3. 3번부터 5번까지의 미션은 Numpy를 이용해서 정답값을 예측해보는 linear regression을 구현해보는 미션입니다. 첫번째 단계로 데이터를 준비해보도록 하겠습니다. 아래와 같이 데이터가 주어져있을 때, **경사하강법을 위한 데이터를 분리**해보세요.
- 주어진 xy 데이터를 이용해서 학습과 정답 데이터를 준비해보세요.
- \*추가 수정* 문제에서 주어진 xy에서 대괄호를 한 번 더 묶어주어야 문제 해결이 가능합니다.  (차원 관련) (np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

```python
import numpy as np
xy = np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])
x_train = # TODO
y_train = # TODO
```
```bash
>>> print(x_train, x_train.shape)
>>> print(y_train, y_train.shape)
[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60] (6,)
```

### A3.

In [ ]:
import numpy as np

# 주어진 xy 데이터 
xy = np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

# training을 위한 x, y 데이터 분리
x_train = xy[0] # 첫번째 차원의 0번 index
y_train = xy[1] # 첫번째 차원의 1번 index

# x_train, y_train 출력
print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


### Q4. **경사 하강법 구현을 위해서 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의**해보세요. 여기서 구현한 weight와 bias는 linear regression 계산을 진행할 때, 직선의 기울기와 y 절편의 값이 됩니다.
- numpy 내의 random 함수를 이용해보세요.

```python
beta_gd = #TODO
bias = #TODO
```
```bash
# 출력 예시
>>> print(beta_gd, bias)
# random 값이어서 값이 다를 수 있습니다. 같은형태로 나오면 됩니다.
[0.75373235] [0.94214468]
```

### A4.

In [ ]:
# 임의의 값으로 weight, bias의 초기값 설정
# 1차원의 numpy array 생성
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

# weight, bias 출력
print(beta_gd, bias)

[0.12296025] [0.15985076]


### Q5. 이제 최종적으로 **linear regression을 경사하강법으로 학습하는 코드**를 구현해봅시다. 경사하강법 구현을 위한 학습 loop를 구현해보세요. 최종적으로 100회 반복했을 시의 결과를 출력하세요.
- 단 Error는 차이의 제곱을 이용해서 계산해주세요.
- Gradient 값은 우리가 예측하는 각 변수에 대한 미분값입니다.

```python
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
[3., 6., 9., 12., 15., 18.]])

x_train = # Q3
y_train = # Q3

beta_gd = # Q4
bias = # Q4

learning_rate = 0.01

for i in range(1000):
    # TODO

    if i % 100 == 0:
        print('Epoch ([:10d]/1000) error: [:10f], beta_gd [:10f], bias:[:10f]'.format(i, error, beta_gd.item(), bias.item()))
```
```bash
# 출력 예시
>>>
Epoch (         0/1000) error: 514.645910, beta_gd   4.768506, bias:  1.761048
Epoch (       100/1000) error:   0.023560, beta_gd   2.967780, bias:  0.139757
Epoch (       200/1000) error:   0.000281, beta_gd   2.996436, bias:  0.015260
Epoch (       300/1000) error:   0.000003, beta_gd   2.999611, bias:  0.001667
Epoch (       400/1000) error:   0.000000, beta_gd   2.999957, bias:  0.000182
Epoch (       500/1000) error:   0.000000, beta_gd   2.999995, bias:  0.000020
Epoch (       600/1000) error:   0.000000, beta_gd   2.999999, bias:  0.000002
Epoch (       700/1000) error:   0.000000, beta_gd   3.000000, bias:  0.000000
Epoch (       800/1000) error:   0.000000, beta_gd   3.000000, bias:  0.000000
Epoch (       900/1000) error:   0.000000, beta_gd   3.000000, bias:  0.000000
```

### A5.

In [ ]:
import numpy as np

# 주어진 xy 좌표 array
xy = np.array([[1., 2., 3., 4., 5., 6.],
[3., 6., 9., 12., 15., 18.]])

# Q3 - 1번째 차원의 0번 1번 index로 분리
x_train = xy[0]
y_train = xy[1]

# Q4 - numpy random함수를 사용하여 1차원의 값으로 weight와 bias 초기화
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

# 학습률 지정
learning_rate = 0.01
# 학습을 위한 epoch 지정
epoch = 1000

for i in range(epoch):
    # linear regression을 위한 경사하강법 학습 코드
    # 정답값과 예측값 간의 error를 최소화 -> 목적식
    # 실제 error는 제곱해서 사용, 여기서는 error를 미분했을 때의 값 {f(g(x))}' = f'(g(x))g'(x) 에서 f'(g(x))
    error = (y_train - (x_train * beta_gd + bias))
    # MSE(Mean Squared Error)
    loss = np.sum(error**2)
    # 목적식을 beta_gd, bias로 미분
    gradient_beta = -2 * np.transpose(error) @ x_train # sum 구해주기 위해 transpose 해주고 행렬곱 연산
    gradient_bias = -2 * np.sum(error) # 미분하면 bias가 1이되고 나머지 term은 소거됨

    # 경사 하강법 적용 부분
    beta_gd = beta_gd - learning_rate * gradient_beta 
    bias = bias - learning_rate * gradient_bias 

    # 100 epoch 단위로 log 출력
    if i % 100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f}, beta_gd {:10f}, bias:{:10f}'.format(i, loss.item(), beta_gd.item(), bias.item()))

Epoch (         0/1000) error: 514.645910, beta_gd   4.768506, bias:  1.761048
Epoch (       100/1000) error:   0.023560, beta_gd   2.967780, bias:  0.139757
Epoch (       200/1000) error:   0.000281, beta_gd   2.996436, bias:  0.015260
Epoch (       300/1000) error:   0.000003, beta_gd   2.999611, bias:  0.001667
Epoch (       400/1000) error:   0.000000, beta_gd   2.999957, bias:  0.000182
Epoch (       500/1000) error:   0.000000, beta_gd   2.999995, bias:  0.000020
Epoch (       600/1000) error:   0.000000, beta_gd   2.999999, bias:  0.000002
Epoch (       700/1000) error:   0.000000, beta_gd   3.000000, bias:  0.000000
Epoch (       800/1000) error:   0.000000, beta_gd   3.000000, bias:  0.000000
Epoch (       900/1000) error:   0.000000, beta_gd   3.000000, bias:  0.000000
